name: Performance Baseline

on:
  workflow_dispatch:
  push:
    branches: [heidi/performance-baselines-2]
  pull_request:

jobs:
  backend-build-baseline:
    name: Backend Build Baseline Run ${{ matrix.run }} 🏗️
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        run: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Measure backend build duration
        run: |
          start_time=$(date +%s)
          ./gradlew classes jar bootJar
          status=$?
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo $duration > backend_build_duration_${{ matrix.run }}.txt
          exit $status
      - name: Move backend build duration report
        run: |
          mkdir -p build_durations
          mv backend_build_duration_${{ matrix.run }}.txt build_durations/backend_build_duration_${{ matrix.run }}.txt
      - name: Upload backend build duration report
        uses: actions/upload-artifact@v4
        with:
          name: backend_build_duration_report_${{ matrix.run }}
          path: build_durations/

  frontend-build-baseline:
    name: Frontend Build Baseline Run ${{ matrix.run }} 🏗️
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        run: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Measure frontend build duration
        run: |
          start_time=$(date +%s)
          ./gradlew buildWebapp
          status=$?
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo $duration > frontend_build_duration_${{ matrix.run }}.txt
          exit $status
        env:
          TOLGEE_API_KEY: ${{secrets.TOLGEE_API_KEY}}
          TOLGEE_API_URL: ${{secrets.TOLGEE_API_URL}}
      - name: Move frontend build duration report
        run: |
          mkdir -p build_durations
          mv frontend_build_duration_${{ matrix.run }}.txt build_durations/frontend_build_duration_${{ matrix.run }}.txt
      - name: Upload frontend build duration report
        uses: actions/upload-artifact@v4
        with:
          name: frontend_build_duration_report_${{ matrix.run }}
          path: build_durations/

  aggregate-backend-build-durations:
    name: Aggregate Backend Build Durations
    runs-on: ubuntu-24.04
    needs: backend-build-baseline
    steps:
      - name: Download all backend build duration artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: backend_build_duration_report_*
          path: build_durations

      - name: Aggregate durations into one file
        run: |
          cat build_durations/backend_build_duration_report_*/backend_build_duration_*.txt > backend_build_durations.txt

      - name: Upload aggregated backend build durations
        uses: actions/upload-artifact@v4
        with:
          name: backend_build_durations
          path: backend_build_durations.txt

  aggregate-frontend-build-durations:
    name: Aggregate Frontend Build Durations
    runs-on: ubuntu-24.04
    needs: frontend-build-baseline
    steps:
      - name: Download all frontend build duration artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: frontend_build_duration_report_*
          path: build_durations

      - name: Aggregate durations into one file
        run: |
          cat build_durations/frontend_build_duration_report_*/frontend_build_duration_*.txt > frontend_build_durations.txt

      - name: Upload aggregated frontend build durations
        uses: actions/upload-artifact@v4
        with:
          name: frontend_build_durations
          path: frontend_build_durations.txt
