name: Performance Baseline

on:
  workflow_dispatch:
  push:
    branches: [heidi/performance-baselines-2]
  pull_request:

jobs:
  backend-build-baseline:
    name: Backend Build Baseline 🏗️
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Measure backend build duration
        run: |
          rm -f backend_build_durations.txt
          for i in {1..10}; do
            echo "Run $i"
            # Clean up any build and gradle cache
            rm -rf backend/build
            rm -rf ~/.gradle
            start_time=$(date +%s)
            ./gradlew classes jar bootJar --no-daemon
            status=$?
            end_time=$(date +%s)
            duration=$((end_time - start_time))
            echo $duration >> backend_build_durations.txt
            if [ $status -ne 0 ]; then
              echo "Build failed on iteration $i"
              exit $status
            fi
          done

      - name: Upload backend build duration report
        uses: actions/upload-artifact@v4
        with:
          name: backend_build_durations
          path: backend_build_durations.txt

  frontend-build-baseline:
    name: Frontend Build Baseline 🏗️
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Measure frontend build duration
        run: |
          rm -f frontend_build_durations.txt
          for i in {1..10}; do
            echo "Run $i"
            rm -rf webapp/build
            rm -rf ~/.gradle
            start_time=$(date +%s)
            ./gradlew buildWebapp --no-daemon
            status=$?
            end_time=$(date +%s)
            duration=$((end_time - start_time))
            echo $duration >> frontend_build_durations.txt
            if [ $status -ne 0 ]; then
              echo "Build failed on iteration $i"
              exit $status
            fi
          done
        env:
          TOLGEE_API_KEY: ${{secrets.TOLGEE_API_KEY}}
          TOLGEE_API_URL: ${{secrets.TOLGEE_API_URL}}

      - name: Upload frontend build duration report
        uses: actions/upload-artifact@v4
        with:
          name: frontend_build_durations
          path: frontend_build_durations.txt
