name: Security Scan

on:
  push:
    branches: [main, test-codeql]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 4 * * 1'  # Weekly on Monday

jobs:
  codeql:
    name: CodeQL Analysis (TypeScript)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for TypeScript changes
        id: ts_changes
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "run_codeql=true" >> "$GITHUB_OUTPUT"
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '\.ts$|\.tsx$'; then
            echo "run_codeql=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_codeql=false" >> "$GITHUB_OUTPUT"
          fi


      - name: Initialize CodeQL
        if: steps.ts_changes.outputs.run_codeql == 'true'
        uses: github/codeql-action/init@v3
        with:
          languages: typescript

      - name: Perform CodeQL Analysis
        if: steps.ts_changes.outputs.run_codeql == 'true'
        uses: github/codeql-action/analyze@v3

        
  detekt:
    name: Detekt Analysis (Kotlin)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Check for Kotlin changes
        id: kotlin_changes
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "run_detekt=true" >> "$GITHUB_OUTPUT"
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '\.kt$|\.kts$'; then
            echo "run_detekt=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_detekt=false" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Run Detekt
        if: steps.kotlin_changes.outputs.run_detekt == 'true'
        run: ./gradlew detektAll --continue

      - name: Upload all Detekt HTML reports
        if: steps.kotlin_changes.outputs.run_detekt == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: '**/build/reports/detekt/*.html'